server: # \u670D\u52A1\u7AEF\u53E3\u548C\u5730\u5740
  port: 8080
  address: 127.0.0.1

spring:
  datasource: # 在\u6570\u636E\u5E93\u76F8\u5173
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3380/ai_check
    username: root
    password: 123654
  web:
    resources: #优先访问static目录，不存在则访问本地D盘
      static-locations: [ classpath:/public/,file:D:/Warehouse/file/,classpath:/resources/,classpath:/static/ ]
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 200MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8



file:
  upload-path: D:/Warehouse/file/fwwb202403/

